### ISSUE TITLE
AVR firmware reboot error when clearing EStop

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#114]
Running Version 0.3.11

I accidentally attempted to home the Z axis with the limit switch disconnected. It ultimately ran into the stop and the motor stalled. Then, I clicked Emergency Stop and the motor stopped. I then clicked Estop again to clear the Etop. This causes the following Error message to pop up:

error | Comm | src/command.c:211 | 6 | Machine alarmed - Command not processed
-- | -- | -- | -- | --
error | Comm | Comm.py:198 | 1 | Unexpected AVR firmware reboot
warning | Comm | Comm.py:187 | 1 | Unterminated string starting at: line 1 column 24 (char 23), data: {"level":"error","msg":"!m->preppe
warning | Comm | Comm.py:171 | 1 | 'utf-8' codec can't decode byte 0xff in position 38: invalid start byte: b'd","code":4,"where":"src/motor.c:291"}\xff'
error | Comm | src/motor.c:291 | 3 | !m->prepped
warning | Mach | Mach.py:177 | 1 | Cannot home c
warning | Mach | Mach.py:177 | 1 | Cannot home b
warning | Mach | Mach.py:177 | 1 | Cannot home a

I acknowledged the error and the error window closed. The Estop did not clear, so I clicked it again. The error message re-appeared, and this time the Estop cleared. I acknowledged the message once again and everything seemed to be back to normal.

This is not a critical problem since it occurs as a result of not having the limit switch connected, but I thought I should document it since it caused the AVR to reboot.

**Comment by jcoffland** [comment]
error | Comm | src/command.c:211 | 6 | Machine alarmed - Command not processed
 -- | -- | -- | -- | --

This  needs to be downgraded to a warning or info message.  When the machine is in EStop many commands are rejected so these errors are expected.

error | Comm | Comm.py:198 | 1 | Unexpected AVR firmware reboot
-- | -- | -- | -- | --

Here the reboot should have been expected since the AVR always reboots when you hit EStop.  I need to work on the unexpected reboot notices.

warning | Comm | Comm.py:187 | 1 | Unterminated string starting at: line 1 column 24 (char 23), data: {"level":"error","msg":"!m->preppe
-- | -- | -- | -- | --
warning | Comm | Comm.py:171 | 1 | 'utf-8' codec can't decode byte 0xff in position 38: invalid start byte: b'd","code":4,"where":"src/motor.c:291"}\xff'

These are caused by a serial buffer overrun.  The two messages are actually the RPi failing to parse the ``!m->prepped`` error because it was split in half.  The message coming from the AVR should have looked like this: ``{"level":"error","msg":"!m->prepped","code":4,"where":"src/motor.c:291"}\n``.  Instead it came through in two parts like this:
 - ``{"level":"error","msg":"!m->preppe\n``
 - ``d","code":4,"where":"src/motor.c:291"}\xff``

I'm not quite sure how this happens or how we end up with a ``\xff`` (aka 0xff) byte at the end.  This only seems to occur for errors that are emitted in interrupts on the AVR.

error | Comm | src/motor.c:291 | 3 | !m->prepped
-- | -- | -- | -- | --

This was caused by the EStop.  I believe I've solved this by implementing a more through shutdown of the stepper drive system on estop.

warning | Mach | Mach.py:177 | 1 | Cannot home c
-- | -- | -- | -- | --
warning | Mach | Mach.py:177 | 1 | Cannot home b
warning | Mach | Mach.py:177 | 1 | Cannot home a

These are expected.
