### ISSUE TITLE
Laser Cutting Program fails

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#159]
When running t2laser_add-g_greyscale.nc, (which is included in the attached zip file), my machine makes some large bangs and then fails altogether with a message that says "Invalid command". The program seems to run fine for a short period, then the bangs start.

When I lower the feed rate from 1000 to 500 mm/minute, the program completes successfully with no bangs or error messages.

[t2laser.zip](https://github.com/buildbotics/bbctrl-firmware/files/2520096/t2laser.zip)

**Comment by jcoffland** [comment]
Yes, I figured this out last night on my hike.  The new code I added to the planner which collapses moves which are so short that they clog up the move processing won't collapse moves if state changes.  In this case, the state that's changing is the S value.  So the move is linear but it's broken up into many very small moves in order to change the S value.  Lowering the speed reduces the rate at which they are fed into the planner.  Ideally, the planner would recognize that the moves can be collapsed and collapse them but use some sort of specialized notation to also record the timing of the S value changes.
