### ISSUE TITLE
feed rate mis interpreted

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#173]
Rocky Evans reported this problem. He has been doing some beta testing for me. He says that the problem did not happen in 0.4.1-beta, but it is occurring in 0.4.2-beta.

When executing the following line of code, the feed rate is only 0.39 inches/minute. It should be 10 inches per minute.

    G90 G54 G20 G17 G1 F10.0 X3.1 Y2.5

It is worth noting that .39 inches per minute is 10 mm per minute, but the G20 statement in the line specifies Imperial units. This may be related to issue #172 as it seems to indicate trouble with specifying the feed rate on the same line as moves too.

Rocky also reported that he let this run for a while and eventually there was a loud popping sound, so he stopped it. Fortunately, there was no apparent damage to the controller or his machine.

**Comment by jcoffland** [comment]
Since ``G20`` is executed after ``F10.0`` it will be interpreted as 10mm not 10in.  This is how GCode works.  See http://linuxcnc.org/docs/html/gcode/overview.html#_g_code_order_of_execution

However, there was an issue with the controller always switching back to the configured default units.  This is controlled on the ``Settings`` page.  I've commited a new 0.4.2 beta which lets it keep the same units between MDI calls.  The default should only be applied when the controller first starts now.
